version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=demo
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_HOST=db
      - DB_NAME=demo
      - DB_PORT=5432
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - VITE_API_URL=http://localhost:3000/graphql
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - frontend

networks:
  backend:
  frontend:
